- name: set network_args fact
  set_fact:
    network_args: >-
      -e /usr/share/openstack-tripleo-heat-templates/environments/network-isolation.yaml
      -e /usr/share/openstack-tripleo-heat-templates/environments/net-single-nic-with-vlans.yaml
      -e $HOME/network-environment.yaml
  when: network_isolation

- name: enable pacemaker
  set_fact:
    pacemaker_args: >-
      -e /usr/share/openstack-tripleo-heat-templates/environments/puppet-pacemaker.yaml
  when: enable_pacemaker
